name = "PolynomialModelReductionDataset"
uuid = "e73a8ff0-27fc-4bea-a65d-4cea79111efd"
authors = ["smallpondtom <tkoike45@gmail.com>"]
version = "0.1.2"

[deps]
DocStringExtensions = "ffbed154-4ef7-542d-bbb7-c09d3a79fcae"
FFTW = "7a1cc6ca-52ef-59f5-83cd-3a7055c09341"
Kronecker = "2c470bb0-bcc8-11e8-3dad-c9649493f05e"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"
UniqueKronecker = "dd29a912-d12a-442e-ae57-6933397c0393"

[compat]
DocStringExtensions = "0.9, 1.0"
FFTW = "1.8, 1.9"
Kronecker = "0.5, 0.6"
SparseArrays = "1.6, 1.7, 1.8, 1.9, 1.10, 1.11, 1.12"
UniqueKronecker = "0.1.0, 0.2.0"
julia = "1.8, 1.9, 1.10, 1.11"
